version: "3.7"

services:
  certbot:
    container_name: nginx-certbot
    entrypoint: certbot certonly --standalone -m ${CERT_EMAIL} --agree-tos -d luna-cloud.licham.io -d download.licham.io -d georgesr.triciabatessmith.com
    image: certbot/certbot
    ports:
      - 80:80/tcp
    volumes:
      - cert-storage:/etc/letsencrypt
  nginx:
    build:
      context: .
    container_name: nginx-frontend
    ports:
      - 443:443/tcp
    restart: unless-stopped
    volumes:
      - cert-storage:/etc/letsencrypt
  download:
    container_name: nginx-download
    image: nginx:latest
    volumes:
      - /mnt/ssd/volumes/nginx-proxy/download:/usr/share/nginx/html:ro
    restart: unless-stopped
  ddclient:
    image: linuxserver/ddclient:latest
    container_name: "ddclient-omnibus"
    volumes:
      - "./ddclient.conf:/config/ddclient.conf"
    restart: unless-stopped
volumes:
  cert-storage:
